# Generated migration for medications app

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rxnorm_code', models.CharField(help_text='RxNorm code', max_length=20, unique=True)),
                ('ndc_code', models.CharField(blank=True, help_text='NDC code', max_length=20)),
                ('generic_name', models.CharField(max_length=200)),
                ('brand_names', models.JSONField(default=list, help_text='List of brand names')),
                ('category', models.CharField(choices=[('analgesic', 'Analgesics/Pain Relief'), ('antibiotic', 'Antibiotics'), ('antihypertensive', 'Antihypertensives'), ('antidiabetic', 'Antidiabetics'), ('anticoagulant', 'Anticoagulants'), ('cardiovascular', 'Cardiovascular'), ('respiratory', 'Respiratory'), ('gastrointestinal', 'Gastrointestinal'), ('psychiatric', 'Psychiatric/Neurological'), ('endocrine', 'Endocrine/Hormones'), ('antiinflammatory', 'Anti-inflammatory'), ('immunosuppressant', 'Immunosuppressants'), ('vitamin', 'Vitamins/Supplements'), ('other', 'Other')], max_length=50)),
                ('drug_class', models.CharField(blank=True, help_text='Pharmacological class', max_length=100)),
                ('form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('liquid', 'Liquid/Solution'), ('injection', 'Injection'), ('cream', 'Cream/Ointment'), ('patch', 'Patch'), ('inhaler', 'Inhaler'), ('drops', 'Drops'), ('suppository', 'Suppository'), ('powder', 'Powder'), ('spray', 'Spray'), ('other', 'Other')], max_length=50)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('iv', 'Intravenous (IV)'), ('im', 'Intramuscular (IM)'), ('subq', 'Subcutaneous'), ('topical', 'Topical'), ('inhalation', 'Inhalation'), ('rectal', 'Rectal'), ('ophthalmic', 'Ophthalmic'), ('otic', 'Otic (Ear)'), ('nasal', 'Nasal'), ('sublingual', 'Sublingual'), ('transdermal', 'Transdermal'), ('other', 'Other')], max_length=50)),
                ('strength', models.CharField(help_text='e.g., 500mg, 10mg/5mL', max_length=100)),
                ('unit', models.CharField(help_text='Unit of measure', max_length=50)),
                ('typical_dose_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('typical_dose_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_daily_dose', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('frequency_options', models.JSONField(default=list, help_text='Common frequencies')),
                ('contraindications', models.TextField(blank=True)),
                ('warnings', models.TextField(blank=True)),
                ('side_effects', models.TextField(blank=True)),
                ('is_controlled', models.BooleanField(default=False)),
                ('controlled_schedule', models.CharField(blank=True, help_text='DEA Schedule (II-V)', max_length=10)),
                ('requires_monitoring', models.BooleanField(default=False)),
                ('monitoring_parameters', models.TextField(blank=True)),
                ('is_high_alert', models.BooleanField(default=False, help_text='High-alert medication')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medication',
                'verbose_name_plural': 'Medication Catalog',
                'ordering': ['generic_name'],
            },
        ),
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('contraindicated', 'Contraindicated')], max_length=20)),
                ('description', models.TextField()),
                ('clinical_effects', models.TextField(blank=True)),
                ('management', models.TextField(blank=True, help_text='How to manage this interaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drug_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_drug_a', to='medications.medicationcatalog')),
                ('drug_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_drug_b', to='medications.medicationcatalog')),
            ],
            options={
                'ordering': ['-severity', 'drug_a__generic_name'],
                'unique_together': {('drug_a', 'drug_b')},
            },
        ),
        migrations.CreateModel(
            name='PatientAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen_type', models.CharField(choices=[('drug', 'Drug'), ('drug_class', 'Drug Class'), ('ingredient', 'Ingredient')], default='drug', max_length=20)),
                ('allergen_name', models.CharField(max_length=200)),
                ('reaction_type', models.CharField(choices=[('allergy', 'Allergy'), ('intolerance', 'Intolerance'), ('adverse_reaction', 'Adverse Reaction')], default='allergy', max_length=20)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('life_threatening', 'Life-Threatening')], max_length=20)),
                ('reaction_description', models.TextField(help_text='Description of reaction')),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_by', models.CharField(blank=True, max_length=200)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(blank=True, help_text='Link to specific medication if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='medications.medicationcatalog')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_allergies', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Patient Allergy',
                'verbose_name_plural': 'Patient Allergies',
                'ordering': ['-severity', 'allergen_name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_number', models.CharField(max_length=50, unique=True)),
                ('fhir_id', models.CharField(blank=True, help_text='FHIR MedicationRequest ID', max_length=100)),
                ('dose_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dose_unit', models.CharField(max_length=50)),
                ('route', models.CharField(max_length=50)),
                ('frequency', models.CharField(help_text='e.g., BID, TID, Q8H', max_length=100)),
                ('frequency_hours', models.IntegerField(blank=True, help_text='Hours between doses', null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('quantity_prescribed', models.IntegerField(blank=True, null=True)),
                ('refills_allowed', models.IntegerField(default=0)),
                ('refills_remaining', models.IntegerField(default=0)),
                ('prn_reason', models.CharField(blank=True, help_text='Reason for PRN use', max_length=200)),
                ('max_prn_doses_per_day', models.IntegerField(blank=True, null=True)),
                ('indication', models.TextField(blank=True, help_text='Reason for prescription')),
                ('diagnosis_codes', models.JSONField(default=list, help_text='ICD-10 codes')),
                ('special_instructions', models.TextField(blank=True)),
                ('prescriber_name', models.CharField(max_length=200)),
                ('prescriber_id', models.CharField(blank=True, max_length=100)),
                ('prescriber_npi', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('discontinued', 'Discontinued'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT'), ('prn', 'PRN (As Needed)')], default='routine', max_length=20)),
                ('pharmacy_notes', models.TextField(blank=True)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('dispensed_by', models.CharField(blank=True, max_length=200)),
                ('allergy_check_passed', models.BooleanField(default=False)),
                ('interaction_check_passed', models.BooleanField(default=False)),
                ('interaction_warnings', models.JSONField(default=list)),
                ('hold_reason', models.TextField(blank=True)),
                ('held_at', models.DateTimeField(blank=True, null=True)),
                ('held_by', models.CharField(blank=True, max_length=200)),
                ('discontinued_reason', models.TextField(blank=True)),
                ('discontinued_at', models.DateTimeField(blank=True, null=True)),
                ('discontinued_by', models.CharField(blank=True, max_length=200)),
                ('prescribed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='medications.medicationcatalog')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-prescribed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'status'], name='medications_patient_5c6e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['prescription_number'], name='medications_prescri_5d6c2b_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status', 'start_date'], name='medications_status_4e6c3e_idx'),
        ),
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, help_text='FHIR MedicationAdministration ID', max_length=100)),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('given', 'Given'), ('not_given', 'Not Given'), ('refused', 'Refused'), ('held', 'Held'), ('missed', 'Missed')], default='scheduled', max_length=20)),
                ('administered_at', models.DateTimeField(blank=True, null=True)),
                ('administered_by', models.CharField(blank=True, max_length=200)),
                ('administered_by_id', models.CharField(blank=True, max_length=100)),
                ('dose_given', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dose_unit', models.CharField(blank=True, max_length=50)),
                ('route_given', models.CharField(blank=True, max_length=50)),
                ('site', models.CharField(blank=True, help_text='Administration site', max_length=100)),
                ('not_given_reason', models.CharField(blank=True, choices=[('patient_refused', 'Patient Refused'), ('patient_unavailable', 'Patient Unavailable'), ('held_per_protocol', 'Held Per Protocol'), ('held_per_provider', 'Held Per Provider Order'), ('npo', 'NPO'), ('adverse_reaction', 'Adverse Reaction'), ('medication_unavailable', 'Medication Unavailable'), ('documentation_error', 'Documentation Error'), ('other', 'Other')], max_length=50)),
                ('not_given_details', models.TextField(blank=True)),
                ('witness_name', models.CharField(blank=True, help_text='For high-alert meds', max_length=200)),
                ('witness_id', models.CharField(blank=True, max_length=100)),
                ('patient_response', models.TextField(blank=True)),
                ('vital_signs_before', models.JSONField(blank=True, default=dict)),
                ('vital_signs_after', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to='medications.prescription')),
            ],
            options={
                'verbose_name': 'Medication Administration',
                'verbose_name_plural': 'Medication Administrations',
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.AddIndex(
            model_name='medicationadministration',
            index=models.Index(fields=['prescription', 'scheduled_time'], name='medications_prescri_0b9a1f_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationadministration',
            index=models.Index(fields=['status', 'scheduled_time'], name='medications_status_f20c4f_idx'),
        ),
    ]
