# Generated by Django 5.2.10 on 2026-01-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='evidence',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='title',
            field=models.CharField(default='Recommendation', max_length=255),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='actions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='rationale',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='severity',
            field=models.CharField(default='info', max_length=20),
        ),
    ]
